loss_fn: l2
T: 350
lr: 1.0e-06
batch_size: 36
sample: true
should_log: true
using_cond: true
display_every: 350
dynamic_threshold: false
use_ema: true
device: cuda:0
pin_memory: true
accumulate_grad_batches: 2
img_size: 64
epochs: 14
train_autoenc: false
enc_loss_coeff: 1.1
