device: auto
pin_memory: true
T: 1000 
lr: 1.0e-04
loss_fn: l2
batch_size: 36
accumulate_grad_batches: 2
img_size: 64
sample: true
should_log: true
epochs: 50
using_cond: true
display_every: 350
dynamic_threshold: true
train_autoenc: false
enc_loss_coeff: 1.1
use_ema: true
